### ISSUE TITLE
Getting an error when using go install on this repository

### ISSUE THREAD

**Issue by jenniferstipe** [DelineaXPM/dsv-sdk-go#27]
**Description of the issue**

I am trying to use the go install command to install this repository, but when I do, I get this error:

```
go install github.com/DelineaXPM/dsv-sdk-go@latest
go: github.com/DelineaXPM/dsv-sdk-go@latest: github.com/DelineaXPM/dsv-sdk-go@v1.0.1: parsing go.mod:
        module declares its path as: github.com/thycotic/dsv-sdk-go
                but was required as: github.com/DelineaXPM/dsv-sdk-go
```
I noticed that @latest seems to pull an old version (1.0.1) by checking go/pkg/mod/github.com/!delinea!x!p!m/dsv-sdk-go@v1.0.1 , so I tried this:

```
go install github.com/DelineaXPM/dsv-sdk-go@v2.0.0
go: github.com/DelineaXPM/dsv-sdk-go@v2.0.0: github.com/DelineaXPM/dsv-sdk-go@v2.0.0: invalid version: go.mod has post-v2 module path "github.com/DelineaXPM/dsv-sdk-go/v2" at revision v2.0.0
```
**Expected behavior**

The go install command should function correctly.

**Actual behavior**

I get the error above.

**Your environment**

WSL2 on Windows 10 using Ubuntu 20.04.5 LTS
go version go1.18.3 linux/amd64

**Steps to reproduce**

1.  Install go in Ubuntu 20.04+
2.  Run the following command:
```
go install github.com/DelineaXPM/dsv-sdk-go@latest
```

**Comment by sheldonhull** [comment]
@jenniferstipe  I'm sorry you didn't get an answer sooner. Just have missed this one. 

This is as SDK still you'd want to use `go get`. Install is Go tooling that can be built as a binary while this would be added to your coffee. Maybe checkout GitHub.com/DelineaXPM/dsv-cli for using DSV with the provided binary?
